server:
  port: 6080
spring:
  cloud:
    gateway:
      routes:
      - id: 163
        uri: https://www.163.com  # 访问http网站，浏览器url不会变（依然是localhost/hello），访问https会变成https://www.163.com
        predicates:
        - Path=/163
        
      - id: web
        uri: lb://spring-boot-web  # 访问http网站，浏览器url不会变（依然是localhost/hello），访问https会变成https://www.163.com
        predicates:
        - Path=/web/rest/**
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-gateway
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*' #打开客户端 Actuator 的监控
eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl.defaultZone: http://localhost:8761/eureka/