server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: 163
        uri: https://www.163.com  # 访问http网站，浏览器url不会变（依然是localhost/hello），访问https会变成https://www.163.com
        predicates:
        - Path=/163
  main:
    allow-bean-definition-overriding: true